# Default values for managed-wildfly-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# The managed server builder image to use

builder:
  images:
    managedServer: quay.io/kabirk/wildfly-managed-server-jdk17:latest
    managedServerBase: quay.io/kabirk/wildfly-managed-server-base-jdk17:latest
    runtime: quay.io/kabirk/wildfly-runtime-jdk17:latest
  featurePacks:
    # Inputs to the managed server builder image
    server:
      GA: org.wildfly:wildfly-galleon-pack
      version: 27.0.0.Alpha5
    cloud:
      GA: org.wildfly.cloud:wildfly-cloud-galleon-pack
      version: 2.0.0.Alpha4
    datasources:
      GA: org.wildfly:wildfly-datasources-galleon-pack
      version: 3.0.0.Beta1

deploy:
  replicas: 2
  tls: {}
  resources: []
  livenessProbe:
    httpGet:
      path: /health/live
      port: admin
  readinessProbe:
    httpGet:
      path: /health/ready
      port: admin
  startupProbe:
    httpGet:
      path: /health/live
      port: admin
    initialDelaySeconds: 5
    failureThreshold: 36
    periodSeconds: 5
  env: []
  envFrom:
  extraContainers: []
  volumes: []
