# Default values for managed-wildfly-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# The managed server builder image to use
managedServerImage: quay.io/kabirk/wildfly-managed-server-jdk17:latest

# The WildFly runtime inmage
runtimeImage: quay.io/kabirk/wildfly-runtime-jdk17:latest

# Inputs to the managed server builder image
serverFeaturePackGA: org.wildfly:wildfly-galleon-pack
serverFeaturePackVersion: 27.0.0.Alpha5
cloudFeaturePackGA: org.wildfly.cloud:wildfly-cloud-galleon-pack
cloudFeaturePackVersion: 2.0.0.Alpha4
datasourcesFeaturePackGA: org.wildfly:wildfly-datasources-galleon-pack
datasourcesFeaturePackVersion: 3.0.0.Beta1

deploy:
  replicas: 2
  tls: {}
  resources: []
  livenessProbe:
    httpGet:
      path: /health/live
      port: admin
  readinessProbe:
    httpGet:
      path: /health/ready
      port: admin
  startupProbe:
    httpGet:
      path: /health/live
      port: admin
    initialDelaySeconds: 5
    failureThreshold: 36
    periodSeconds: 5
  env: []
  envFrom:
  extraContainers: []
  volumes: []
