# Default values for managed-wildfly-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

applicationName: kabir-test
applicationNamespace: kkhan1-dev
managedServerImage: quay.io/kabirk/wildfly-managed-server-jdk17:latest
runtimeImage: quay.io/wildfly/wildfly-runtime-jdk17:latest