########################################################################################################################
# Update the application deployment
# Takes a war uploaded by the user, and copy it into the provisioned server in an image in
#  <app-name>-wildfly-runtime:latest
# The resulting image is tagged and pushed to <app-name>-deployment:latest which will update the application
########################################################################################################################
apiVersion: v1
kind: List
items:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: {{ .Release.Name }}-update-build
      labels:
        app: {{ .Release.Name }}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: {{ .Release.Name }}:latest
      postCommit: {}
      resources: {}
      source:
        type: Binary
        binary:
          asFile: ROOT.war
        dockerfile: |-
          # FROM gets overwritten by the dockerStrategy
          FROM <app-name>-runtime-server:latest        
          COPY ROOT.war $JBOSS_HOME/standalone/deployments/ROOT.war
          # Workaround: For some reason 'COPY -–chown=jboss:root ...' does not work here, so change permissions manually 
          USER root
          RUN chown jboss:root $JBOSS_HOME/standalone/deployments/ROOT.war
          USER jboss
          # Workaround - END
          RUN chmod -R ug+rwX $JBOSS_HOME
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: {{ .Release.Name }}-runtime-server:latest
        type: Docker