########################################################################################################################
# Provisions a server using the information in the war META-INF/server-config.xml in the <app-name>-deployment:latest
# image.
# The resulting image is based on the managed server builder image, and is tagged and pushed to
#  <app-name>-provisioned-server:latest
########################################################################################################################
apiVersion: v1
kind: List
items:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: {{ .Release.Name }}-wildfly-managed-server
      labels:
        app: {{ .Release.Name }}
    spec:
      lookupPolicy:
        local: false
      tags:
        - from:
            kind: DockerImage
            name: {{ .Values.managedServerImage }}
          generation: null
          importPolicy: { }
          name: latest
          referencePolicy:
            type: ""
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: {{ .Release.Name }}-provisioned-server
      labels:
        app: {{ .Release.Name }}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: {{ .Release.Name }}-provisioned-server-build
      labels:
        app: {{ .Release.Name }}
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: {{ .Release.Name }}-provisioned-server:latest
      postCommit: { }
      resources: { }
      source:
        images:
          - from:
              kind: ImageStreamTag
              name: {{ .Release.Name }}-deployment:latest
              namespace: {{ .Release.Namespace }}
            paths:
              - destinationDir: artifacts
                sourcePath: /tmp/artifacts/ROOT.war
        contextDir: artifacts
        type: Image
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: {{ .Release.Name }}-wildfly-managed-server:latest
          env:
            - name: MANAGED_SERVER_SERVER_FEATURE_PACK_GA
              value: {{ .Values.serverFeaturePackGA }}
            - name: MANAGED_SERVER_SERVER_FEATURE_PACK_VERSION
              value: {{ .Values.serverFeaturePackVersion }}
            - name: MANAGED_SERVER_CLOUD_FEATURE_PACK_GA
              value: {{ .Values.cloudFeaturePackGA }}
            - name: MANAGED_SERVER_CLOUD_FEATURE_PACK_VERSION
              value: {{ .Values.cloudFeaturePackVersion }}
            - name: MANAGED_SERVER_DATASOURCES_FEATURE_PACK_GA
              value: {{ .Values.datasourcesFeaturePackGA }}
            - name: MANAGED_SERVER_DATASOURCES_FEATURE_PACK_VERSION
              value: {{ .Values.datasourcesFeaturePackVersion }}
        type: Source
      triggers:
        - imageChange:
            from:
              kind: ImageStreamTag
              name: {{ .Release.Name }}-deployment:latest
              namespace: {{ .Release.Namespace }}
          type: ImageChange
