########################################################################################################################
# Provisions a server using the information in the war META-INF/server-config.xml in the <app-name>-deployment:latest
# image.
# The resulting image is based on the managed server builder image, and is tagged and pushed to
#  <app-name>-provisioned-server:latest
########################################################################################################################
apiVersion: v1
kind: List
items:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: {{ .Release.Name }}-wildfly-managed-server
      labels:
        app: {{ .Release.Name }}
    spec:
      lookupPolicy:
        local: false
      tags:
        - from:
            kind: DockerImage
            name: {{ include "common.wildfly.image.builder" . }}
          generation: null
          importPolicy: { }
          name: latest
          referencePolicy:
            type: ""
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: {{ .Release.Name }}-provisioned-server
      labels:
        app: {{ .Release.Name }}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: {{ .Release.Name }}-provisioned-server-build
      labels:
        app: {{ .Release.Name }}
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: {{ .Release.Name }}-provisioned-server:latest
      postCommit: { }
      resources: { }
      source:
        images:
          - from:
              kind: ImageStreamTag
              name: {{ .Release.Name }}-deployment:latest
              namespace: {{ .Release.Namespace }}
            paths:
              - destinationDir: artifacts
                sourcePath: /tmp/artifacts/.
        contextDir: artifacts
        type: Image
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: {{ .Release.Name }}-wildfly-managed-server:latest
          env:
#            - name: "BUILD_LOGLEVEL"
#              value: "5"
            - name: MANAGED_SERVER_SERVER_FEATURE_PACK_GA
              value: {{ .Values.builder.featurePacks.server.GA }}
            - name: MANAGED_SERVER_SERVER_FEATURE_PACK_VERSION
              value: {{ .Values.builder.featurePacks.server.version }}
            - name: MANAGED_SERVER_CLOUD_FEATURE_PACK_GA
              value: {{ .Values.builder.featurePacks.cloud.GA }}
            - name: MANAGED_SERVER_CLOUD_FEATURE_PACK_VERSION
              value: {{ .Values.builder.featurePacks.cloud.version }}
            - name: MANAGED_SERVER_DATASOURCES_FEATURE_PACK_GA
              value: {{ .Values.builder.featurePacks.datasources.GA }}
            - name: MANAGED_SERVER_DATASOURCES_FEATURE_PACK_VERSION
              value: {{ .Values.builder.featurePacks.datasources.version }}
            # BASE_IMAGE_LAYERS is set when preparing the base builder image. We need to unset it here
            # to perform a normal build. Noop for the empty builder image.
            - name: BASE_IMAGE_LAYERS
              value:
        type: Source
      triggers:
        - imageChange:
            from:
              kind: ImageStreamTag
              name: {{ .Release.Name }}-deployment:latest
              namespace: {{ .Release.Namespace }}
          type: ImageChange
